odetta/urls.py
from django.conf.urls import patterns, include, url
from odetta.views import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', home_page),
    url(r'^plot/(?P<model_id>\d+)/(?P<time_step>\d+)/(?P<mu_step>\d+)/(?P<phi_step>\d+)/img/$', plot_img),
    url(r'^plot/(?P<model_id>\d+)/$', plot),
    url(r'^ajax/plot/(?P<model_id>\d+)/upload/$', upload),
    url(r'^ajax/plot/(?P<model_id>\d+)/(?P<time_step>\d+)/$', get_plot_data),
    url(r'^ajax/plot/(?P<model_id>\d+)/(?P<time_step>\d+)/(?P<mu_step>\d+)/$', get_plot_data),
    url(r'^ajax/plot/(?P<model_id>\d+)/(?P<time_step>\d+)/(?P<mu_step>\d+)/(?P<phi_step>\d+)/$', get_plot_data),
    url(r'^ajax/mu/(?P<model_id>\d+)/(?P<time_step>\d+)/(?P<phi_step>\d+)/$', batch_mu_data),
    url(r'^ajax/time/(?P<model_id>\d+)/(?P<mu_step>\d+)/(?P<phi_step>\d+)/$', batch_time_data),
    url(r'^ajax/overplot/(?P<model_id>\d+)/$', ajax_overplot),
    # url(r'^ajax/plot/(?P<id>\d+)/(?P<frame>\d+)/$', get_all_data),
    # url(r'^plot_few/(\d+)/$', plot_few),
    # url(r'^text/$', text),
    url(r'^search/$', search_models),
    url(r'^about/$', about),
    url(r'^fitter/$', fitter),
    url(r'^fitter/results/$',fitter),
    url(r'^download/$',get_zip_file),
    # Examples:
    #url(r'^$', 'odetta.views.home', name='home'),
    #url(r'^odetta/', include('odetta.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^browse/$', browse),
    url(r'^browse/models/(?P<pub_id>\d+)/$', browse),
)

odetta/models.py
from __future__ import unicode_literals
from django.db import models
from django import forms


class Publications(models.Model):
    modeltype = models.CharField(max_length=40, blank = True, verbose_name='Model Type')
    modeldim = models.IntegerField(verbose_name='Model Dimension')
    date_entered = models.DateField(verbose_name='Date Entered')
    citation = models.CharField(max_length=200, blank=True, verbose_name='Citation')
    type = models.CharField(max_length=10, blank = True, verbose_name='Type')
    pub_id = models.IntegerField(primary_key=True, verbose_name='Publication ID')
    fullname = models.CharField(max_length=200,blank=True)
    shortname = models.CharField(max_length=200,blank=True)
    is_public = models.BooleanField()
    metatype = models.CharField(max_length=20, blank=True)
    summary = models.TextField()
    url = models.CharField(max_length=200,blank=True)

    class Meta:
        db_table = 'publications'

class Chi2Test(models.Model):
    fname = models.CharField(max_length=200, blank=True)
    chi2dof = models.FloatField(null=True, blank=True)
    chi2dof_bin = models.FloatField(null=True, blank=True)
    dof = models.IntegerField(null=True, blank=True)
    dofb = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'chi2test'

class Spectra(models.Model):
    model_id = models.IntegerField()
    spec_id = models.IntegerField(primary_key=True)
    t_expl= models.FloatField(null=True,blank=True)
    mu = models.FloatField(null=True,blank=True)
    phi = models.FloatField(null=True, blank=True)
    metatype = models.CharField(max_length=20, blank=True)
    
    class Meta:
        db_table = 'spectra'

class Fluxvals(models.Model):
    spec_id = models.IntegerField(primary_key=True)
    wavelength = models.FloatField()
    luminosity = models.FloatField(null=True, blank=True)
    photon_count = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = 'fluxvals'


class MetaDd2D(models.Model):
    model_id = models.IntegerField(primary_key=True)
    pub_id = models.IntegerField()
    modelname = models.CharField(max_length=40, blank=True)
    mass_wd = models.FloatField(null=True, blank=True)
    percent_carbon = models.FloatField(null=True, blank=True)
    percent_oxygen = models.FloatField(null=True, blank=True)
    n_ignit = models.IntegerField(null=True, blank=True)
    r_min_ignit = models.FloatField(null=True, blank=True)
    cos_alpha = models.FloatField(null=True, blank=True)
    stdev = models.FloatField(null=True, blank=True)
    ka_min = models.FloatField(null=True, blank=True)
    rho_min = models.FloatField(null=True, blank=True)
    rho_max = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = 'meta_dd2d'

    # @property
    # def date_entered(self):
    #     return Models.objects.values("date_entered").get(m_type_id=self.m_type_id)['date_entered']

    # @property
    # def sntype(self):
    #     return Models.objects.values("sntype").get(m_type_id=self.m_type_id)['sntype']

    # @property
    # def citation(self):
    #     return Models.objects.values("citation").get(m_type_id=self.m_type_id)['citation']

    def has_mu(self):
        return Spectra.objects.filter(model_id=self.model_id).distinct("mu").count() > 1

    def has_phi(self):
        return Spectra.objects.filter(model_id=self.model_id).distinct("phi").count() > 1

class MetaNsm1D(models.Model):
    pub_id = models.IntegerField()
    model_id = models.IntegerField(primary_key=True)
    modelname = models.CharField(max_length=40, blank=True)
    m_ej = models.FloatField(null=True, blank=True)
    beta = models.FloatField(null=True, blank=True)
    n = models.FloatField(null=True, blank=True)
    delta = models.FloatField(null=True, blank=True)
    composition = models.CharField(max_length=4)

    class Meta:
        db_table = 'meta_nsm1d'

class LightCurves(models.Model):
    model_id = models.IntegerField()
    lc_id = models.IntegerField(primary_key=True)
    theta = models.FloatField(null=True, blank=True)
    phi = models.FloatField(null=True, blank=True)
    b_lan_max = models.FloatField(null=True, blank=True)
    r_lan_max = models.FloatField(null=True, blank=True)
    i_lan_max = models.FloatField(null=True, blank=True)
    ux_lan_max = models.FloatField(null=True, blank=True)
    v_lan_max = models.FloatField(null=True, blank=True)
    t_b_lan_max = models.FloatField(null=True, blank=True)
    t_r_lan_max = models.FloatField(null=True, blank=True)
    t_i_lan_max = models.FloatField(null=True, blank=True)
    t_ux_lan_max = models.FloatField(null=True, blank=True)
    t_v_lan_max = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = 'lightcurves'

class LCVals(models.Model):
    lc_id = models.IntegerField(primary_key=True)
    t_expl = models.IntegerField()
    b_landolt = models.FloatField(null=True, blank=True)
    r_landolt = models.FloatField(null=True, blank=True)
    i_landolt = models.FloatField(null=True, blank=True)
    ux_landolt = models.FloatField(null=True, blank=True)
    v_landolt = models.FloatField(null=True, blank=True)

    class Meta:
        db_table = 'lcvals'

def get_time_max(model_id):
    return Spectra.objects.filter(model_id=model_id).values("t_expl").distinct("t_expl").order_by("t_expl").count() - 1

def get_mu_max(model_id):
    return Spectra.objects.filter(model_id=model_id).values("mu").distinct("mu").order_by("-mu").count() - 1

def get_phi_max(model_id):
    return Spectra.objects.filter(model_id=model_id).values("phi").distinct("phi").order_by("-phi").count() - 1

def get_time_val(model_id):
    times = []
    for time in Spectra.objects.filter(model_id = model_id).values("t_expl").distinct("t_expl").order_by("t_expl"):
        times.append(time["t_expl"]) 
    return times

def get_mu_val(model_id):
    mu_steps = []
    for mu in Spectra.objects.filter(model_id = model_id).values("mu").distinct("mu").order_by("mu"):
        mu_steps.append(mu["mu"]) 
    return mu_steps

class SearchForm(forms.Form):
    min_mass = forms.IntegerField(required=False, label='Minimum Mass')
    max_mass = forms.IntegerField(required=False, label="Maximum Mass")
    max_lum = forms.IntegerField(required=False, label="Peak Luminosity")

templates/about.html
{% extends "base.html" %}

{% block head %}
	<style type="text/css">
		p img{
			margin:10px;
			float:left;
		}
		h3{
			clear:both;
		}
	</style>
{% endblock head %}

{% block content %}
<div class = "span10 offset1">
	<h1>About Us</h1>
	<h3 id="odetta">What is ODETTA?</h3>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Video hanc mediocritatem acute, delectus disciplinae electram tantum aliquando, aristotelem administrari inermis scaevolam conspectum eius urbanitas claudicare. Vetuit pellat moderatius, aliae mediocritatem imitarentur neque, damna intellegamus notae delectu, inertissimae pertineant faciant tantam, se perpessio indocti utuntur imbutus multam. Posuit amplificarique miserum arbitrium.
		Fabulas meminerimus metuque dicemus, magnum intellegebat iudicat vel antiquitate optime reddidisti ita vitam spernat. Aequitate contumeliae maximasque desiderat vivi iustitiam initia afferre, sapientium arare familiaritatem concordia stultorum brute repetitis, confidere declinatio legat corrupti tenetur aliquid se quisquam dissensio confidet, civitas finiri epicurum futura quocirca benivole idem, vos maiestatis cepisse plus.
		Patet dialectica doctiores labitur dicent imbutus compluribus verissimum locum, labefactetur pedalis exeduntur vidisse, diogenem primos partiendo alteram nos, vivamus pueros ratione tantis sanos disputatum migrare facio cupiditates, crudelis emolumento rem officii moderatio viveremus polyaeno fonte liberae voluit. Quod ingenii, an mollitia eorum studiose hinc consequentis saepe leniter, terentii civitas. Feramus.
		Electis periculis aptius fatendum. Cupiditate iracundiae interrogari morte ingenii consequi potitur firmam antiqua gratissimo, leniat leniat servire, seditione falsis necessarius admonere fana graeco ipsis nullas perciperet, vias consequuntur gratissimo admonitionem temeritas intelleges primo nivem, labitur levius, synephebos panaetium convicia. Scribi ostendit, ornatus laetitia utilitatibus, contra dubio infinito, putent afficit magni.
	</p>
	<h3 id="p1">Terence Sun</h3>
	<p>
		<img src="http://lorempixel.com/150/150/cats/" alt="Profile Picture" title="Person 1" class="img-polaroid">
		Terence is in the undergraduate class of 2017 at Carnegie Mellon University in Pittsburgh, PA studying Electrical and Computer Engineering. In the summer of 2013, Terence worked at NERSC to help create the ODETTA gateway.
	</p>
	<h3 id="p2">Tony Wang</h3>
	<p>
		<img src="http://lorempixel.com/150/150/food/" alt="Profile Picture" title="Person 1" class="img-polaroid">
		Tony Wang is a 17 year old high school graduate going undeclared to UC Berkeley, but is very interested in computer science. He has worked at NERSC for two summers with the Outreach, Software, and Programming group. 
		
	</p>
	<h3 id="p3">Annette Greiner</h3>
	<p>
		<img src="http://lorempixel.com/150/150/animals/" alt="Profile Picture" title="Person 1" class="img-polaroid">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Factis incursione falsi infantes adoptionem cumque cognomen restincto. Dissentias memoriter fit referri potius cupiditate aiunt platone, generibusque terminari. Consequuntur tantum videtur posuit posset, censes modi institutionem angusta satis maius ipsis probet minime, unde laus celeritas gravissimo fortitudinem, fit sequimur perciperet nominavi cibo.
		Vera probatum nostri quicquam videmus depulsa summo e angere, illae maxime imperitorum asperiores facio perinde utilitatibus voluerint censet democritus, maiestatis seiunctum conversam expeteretur viros studiis laudandis. Inmortalibus admissum, atomum ingenia proficiscuntur gaudeat insequitur democritus suscepi curis superstitio theophrasti, sapienter idque recusabo triario, malint hac quamque o relinqueret earumque optari ego.
	</p>
	<h3 id="p4">János Botyánszki</h3>
	<p>
		<img src="http://lorempixel.com/150/150/abstract/" alt="Profile Picture" title="Person 1" class="img-polaroid">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Factis incursione falsi infantes adoptionem cumque cognomen restincto. Dissentias memoriter fit referri potius cupiditate aiunt platone, generibusque terminari. Consequuntur tantum videtur posuit posset, censes modi institutionem angusta satis maius ipsis probet minime, unde laus celeritas gravissimo fortitudinem, fit sequimur perciperet nominavi cibo.
		Vera probatum nostri quicquam videmus depulsa summo e angere, illae maxime imperitorum asperiores facio perinde utilitatibus voluerint censet democritus, maiestatis seiunctum conversam expeteretur viros studiis laudandis. Inmortalibus admissum, atomum ingenia proficiscuntur gaudeat insequitur democritus suscepi curis superstitio theophrasti, sapienter idque recusabo triario, malint hac quamque o relinqueret earumque optari ego.
	</p>
	<h3 id="p4">Daniel Kasen</h3>
	<p>
		<img src="http://lorempixel.com/150/150/people/" alt="Profile Picture" title="Person 1" class="img-polaroid">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Factis incursione falsi infantes adoptionem cumque cognomen restincto. Dissentias memoriter fit referri potius cupiditate aiunt platone, generibusque terminari. Consequuntur tantum videtur posuit posset, censes modi institutionem angusta satis maius ipsis probet minime, unde laus celeritas gravissimo fortitudinem, fit sequimur perciperet nominavi cibo.
		Vera probatum nostri quicquam videmus depulsa summo e angere, illae maxime imperitorum asperiores facio perinde utilitatibus voluerint censet democritus, maiestatis seiunctum conversam expeteretur viros studiis laudandis. Inmortalibus admissum, atomum ingenia proficiscuntur gaudeat insequitur democritus suscepi curis superstitio theophrasti, sapienter idque recusabo triario, malint hac quamque o relinqueret earumque optari ego.
	</p>
</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ODETTA</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen"/>
    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet" media="screen"/>
    <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui-1.10.3.custom.css' %}" />
    <script src="{% static 'js/jquery-ui-1.10.3.custom.js' %}"></script>
    <script type="text/javascript">
    var xPos= 0;
    var yPos= 0;
    var xSpeed = 1;
    var ySpeed = 1;
    var count = 0;
    var scrolling;
    $(document).ready(function(){
        $("header h1").click(function(){
            count++;
            if(count>5){
                scrollBG();
            }
        });
        $("header h3").click(function(){
            scrolling = clearInterval(scrolling);
            count = 0;
        });
        $("#popupbox").dialog({
            autoOpen: false,
            width:450,
            position: {my:"top", at:"top", of:$("#content")},
        });
        $(".popup").click(function(e){
            e.preventDefault();
            $("#popupbox").load($(this).attr("href"), function(){
                $("#popupbox").dialog("open");   
                $(".closedialog").click(function(e){
                    e.preventDefault();
                    $("#popupbox").dialog("close");
                    return false;
                }); 
            });
            return false;
        }); 
    });
    function scrollBG(){
        scrolling = clearInterval(scrolling);
        scrolling = setInterval(function(){
            $("header").css("backgroundPosition", xPos + "px " + yPos+ "px");
            xPos+= xSpeed;
            yPos+= ySpeed;
            if(xPos> 900||xPos<0){
                xSpeed*=-1;
            }
            if(yPos>576|| yPos<0){
                ySpeed*=-1;
            }
        }, 40);
    }
    function validateSearchChars(str){
            var regex = /[^a-zA-Z\_\-\)\(\s\!\@\#\$\%\^\&\*\:\;\'\"\/\\\[\]\{\}\|\=\+]/g;
            if(str.length == 0 || str.search(regex) != -1){
                return false;
            }
            return true;
        }
    </script>
    {% block head %}
        
    {% endblock head %}
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="#">Odetta</a>
                <ul class="nav">
                    <li><a href="/odetta/">Home</a></li>
                    <li><a href="{% url 'odetta.views.browse' %}">Browse Spectra</a></li>
                    <li><a href="{% url 'odetta.views.search_models' %}">Search Spectra</a></li>
                    <li><a href="{% url 'odetta.views.fitter' %}">Fitter</a></li>
                    <li><a href="{% url 'odetta.views.about' %}">About Us</a></li>
                </ul>
            </div>
        </div>
    </div>
    <header>
        <div class="container">
            {% block heading %}
            <h1>ODETTA</h1>
            <h3>Online Database of Extragalactic Transient Theoretical Astrophysics</h3>
            {% endblock %}
        </div>
    </header>
    <div class="container" id = "content">
        {% if breadcrumbs %}                
            <div class="row-fluid">
                <div class="span12">
                    <ul class="breadcrumb">
                        {% for crumb in breadcrumbs %}
                            {% if crumb.active %}
                                <li class="active">{{crumb.name}}</li>
                            {% else %}
                                <li><a href="{{crumb.url}}">{{crumb.name}}</a><span class="divider">/</span></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="row-fluid">
            {% block content %}
                <div class="span10 offset1">
                    <h1>Sample Heading</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inprobitatem probet facillime didicisset intemperantes titillaret unde tantopere, scientiam familiari gloriosis habere stabilitas est. Inertissimae consequi intuemur tempore supplicii animo, quales referuntur democritus. Inhaererent aliae arbitrarer saluti solam necessarius tanta. Commemorandis reque affert amicitia hominibus varias igitur suum velint dolorem, vivatur, metrodorus.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, commodi, consequuntur, fugiat, dolores consectetur eius praesentium aspernatur enim id animi consequatur cum nostrum non dignissimos ad veritatis atque vel magni?
                    </p>
                    <p>
                        Legant requietis probamus doctissimos efficitur voluptatum oritur praetereat, atque argumentandum omnibus philosophiae servata probatus dicit, iudicante iustitiam impeditur, audivi. Innumerabiles confectum pacto definitiones ponendam fore. Ferre aequum corrupisti, viris saluti exorsus falso superstitio, servata summam diu foris dominos dignissimos. Provocarem finxerat atomus disciplinis vacare gloriatur menandri confirmat probaretur putem, renovata.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi, error exercitationem ipsum soluta debitis sint laborum doloribus reiciendis explicabo sit laboriosam quisquam. Facere, tempore, vel nemo provident ex porro expedita!
                    </p>
                </div>
            {% endblock content %}
        </div>
    </div>
    <div id = "popupbox">
    </div>
</body>
</html>

templates/fitter_form.html
{% extends "base.html" %}

{% block head %}
	<style type="text/css">
	form .form-actions{
		text-align: right;
	}
	form label{
		margin-left:1em;
	}
	.form-container{
		padding:1em 2em;
	}
	</style>
	<script type="text/javascript">
	</script>
{% endblock head %}

{% block content %}
	<div class="span10 offset1">
		<h1>Spectrum Fitter</h1>
		<form action="{% url 'odetta.views.fitter' %}" method="post" enctype="multipart/form-data" id = "fitterform">
			{% csrf_token %}
			<div class="form-container">
				<label for="file_upload">
					File to fit: <input type="file" id="file_upload" name="file"/>
				</label>
				<label class="radio">
					<input type="radio" name="fitType" value="0" checked>
					Try all types
				</label>
				<label class="radio">
					<input type="radio" name="fitType" value="1">
					SNIa (Single Degenerate) Explosion
				</label>
				<label class="radio">
					<input type="radio" name="fitType" value="2">
					SNII Explosion
				</label>
				<label class="radio">
					<input type="radio" name="fitType" value="3">
					AGN Accretion
				</label>
				<label class="radio">
					<input type="radio" name="fitType" value="4">
					BH-BH Merger
				</label>
			</div>

			<div class="form-actions">
				<button type="submit" class="btn btn-primary">Find Spectra</button>
				<button type="button" class="btn">Cancel</button>
			</div>
		</form>
	</div>
{% endblock content %}

templates/list_view.html
{% extends "base.html" %}

{% block head %}
    <style type="text/css">
        .result a{
            font-size: 18px;
        }
        .result{
            margin:10px 0;
        }
    </style>
{% endblock %}

{% block content %}
<div class = "span10 offset1">
    <div class="row-fluid">        
        <div class="span12 results">
            {%for x in results%}
                <div class="result">
                    <a href="{{x.url}}">{{x.name}}</a>
                    <div class="details">
                        {{x.details}}
                    </div>
                </div>
            {% endfor %}
            <div class="pagination pagination-centered">
                <ul>
                    <li><a href="?{{q_string}}&page=1">First</a></li>
                    {% if results.has_previous %}
                    <li>
                        <a href="?{{q_string}}&page={{results.previous_page_number}}">Prev</a>
                    </li>
                    {% else %}
                    <li class="disabled">
                        <a href="#">Prev</a>
                    </li>
                    {% endif %}

                    {% for page in page_range %}
                        {% if page == results.number %}
                            <li class="active">
                                <a href="?{{q_string}}&page={{page}}">{{page}}</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="?{{q_string}}&page={{page}}">{{page}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if results.has_next %}
                    <li>
                        <a href="?{{q_string}}&page={{ results.next_page_number }}">Next</a>
                     </li>
                    {% else %}
                    <li class="disabled">
                        <a href="#" class="disabled">Next</a>
                    </li>       
                    {% endif %}
                    <li><a href="?{{q_string}}&page=99999">Last</a></li>
                </ul>   
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block head %}
	<style type="text/css">
		form{
			width:450px;
			padding:1em;
		}
		.result a{
			font-size: 1.2em;
		}
		.result .details{
			padding-left:1em;
		}
		.result small{
			font-size: 0.8em;
			font-variant: small-caps;
		}
		#errormsg{
			display:none;
		}
		#errormsg p, #searcherrormsg p{
			color:red;
			font-size: 16px;
			text-align: center;
		}
	</style>
	<script type="text/javascript">
	$(document).ready(function(){
		$("#search-form").submit(function(e){
			console.log("hi");
			if(validateSearchChars($("#minmass").val()) || validateSearchChars($("#maxmass").val()) || validateSearchChars($("#peaklum").val())){
				e.preventDefault();
				$("#errormsg").css("display","block");
				return false;
			} else{
				$("#errormsg").css("display","none");
				return true;
			}
		});
	});
	</script>
{% endblock head %}

{% block content %}
<div class = "span10 offset3">
	<h1>Spectra Search</h1>
	<form action="/odetta/search/" method="get" class="form-horizontal" id = "search-form">
			<p>
				For the fastest search, please enter in the most amount of fields possible. 
			</p>
			<div class="control-group">
				<p>
					<label class="control-label" for="id_minmass">Minimum Mass: </label>
					<input class="fields" id="minmass" name = "minmass" placeholder = "Leave blank for no min">
				</p>
				<p>
					<label class="control-label" for="id_maxmass">Maximum Mass: </label>
					<input class="fields" id="maxmass" name = "maxmass" placeholder = "Leave blank for no max">
				</p>
				<p>
					<label class="control-label" for="id_maxlum">Peak Luminosity: </label>
					<input class="fields" id="peaklum" name = "peaklum" placeholder = "Leave blank for 0">
				</p>
				<p>
					<label class = "control-label" for="id_modeltype">Model Type: </label>
					<input class = "fields" id = "modeltype" name = "modeltype" placeholder = "Ex: Delayed detonation">
				</p>
			</div>
			<div id = "errormsg">
				<p>
					Incorrect Fields
				</p>
			</div>
			<div id = "searcherrormsg">
				<p>
					{{error}}
				</p>
			</div>
			<div class="control-group">
				<div class="controls">
					<input class="btn" type="submit" value="Search" />					
				</div>
			</div>
	</form>

	{% if results %}
	<div class="span12 results">
		{% for result in results %}
			<div class="result">
				<a href="{% url 'odetta.views.plot' result.model.model_id %}">{{result.model.modelname}}</a>
				<small><a href="{%	url 'odetta.views.plot_img' model_id=result.model.model_id time_step=0 mu_step=0 phi_step=0 %}">img</a></small>
				<div class="details">
					<strong>Publication: {{result.pub.fullname}}</strong><br/>
					Model Name: {{result.model.modelname}}, Mass: {{result.model.mass_wd}}
				</div>
			</div>
		{% endfor %}
		<div class="pagination">
			<ul>
				<li><a href="?{{q_string}}&page=1">First</a></li>
				{% if results.has_previous %}
				<li>
		            <a href="?{{q_string}}&page={{results.previous_page_number}}">Prev</a>
				</li>
		       	{% else %}
		       	<li class="disabled">
		       		<a href="#">Prev</a>
		       	</li>
		        {% endif %}

		        {% for page in page_range %}
		        	{% if page == results.number %}
		        		<li class="active">
		        			<a href="?{{q_string}}&page={{page}}">{{page}}</a>
		        		</li>
		        	{% else %}
		        		<li>
		        			<a href="?{{q_string}}&page={{page}}">{{page}}</a>
		        		</li>
		        	{% endif %}
		        {% endfor %}

				{% if results.has_next %}
				<li>
		            <a href="?{{q_string}}&page={{ results.next_page_number }}">Next</a>
		         </li>
		       	{% else %}
		       	<li class="disabled">
		       		<a href="#" class="disabled">Next</a>
				</li>		
		        {% endif %}
		        <li><a href="?{{q_string}}&page=99999">Last</a></li>
			</ul>	
		</div>
	</div>
	{% endif %}
</div>
{% endblock content %}